/**
 * Auto-update wiring for DeepSeek Harness Desktop.
 *
 * Uses electron-updater. Update metadata (app-update.yml) is generated by
 * electron-builder from the `publish` block and points at GitHub Releases:
 *
 *   Windows  -> NSIS installer (latest.yml, differential updates)
 *   macOS    -> zip (latest-mac.yml; the dmg is install-only, not updatable)
 *
 * macOS caveat: automatic updates require the app to be code-signed with a
 * Developer ID certificate. Unsigned dev builds will skip updates silently.
 */
'use strict';

const { app, dialog, shell } = require('electron');

let initialized = false;
let getWindow = null;

/** Set up listeners. Call once after the main window is created. */
function setupUpdater(windowGetter) {
  getWindow = windowGetter;

  const { autoUpdater } = require('electron-updater');

  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.allowDowngrade = false;
  autoUpdater.channel = process.env.DSH_DESKTOP_UPDATE_CHANNEL || 'latest';

  autoUpdater.on('checking-for-update', () => {
    const w = getWindow && getWindow();
    if (w && !w.isDestroyed()) w.webContents.send('update:status', 'checking');
  });

  autoUpdater.on('update-available', (info) => {
    const w = getWindow && getWindow();
    if (w && !w.isDestroyed()) {
      w.webContents.send('update:status', 'downloading');
      w.webContents.send('update:available', {
        version: info.version,
        releaseName: info.releaseName || null,
      });
    }
  });

  autoUpdater.on('update-not-available', () => {
    const w = getWindow && getWindow();
    if (w && !w.isDestroyed()) w.webContents.send('update:status', 'not-available');
  });

  autoUpdater.on('error', (err) => {
    const w = getWindow && getWindow();
    if (w && !w.isDestroyed()) w.webContents.send('update:error', String(err?.message || err));
  });

  autoUpdater.on('download-progress', (p) => {
    const w = getWindow && getWindow();
    if (w && !w.isDestroyed()) {
      w.webContents.send('update:progress', {
        percent: Math.round(p.percent || 0),
        transferred: p.transferred || 0,
        total: p.total || 0,
      });
    }
  });

  autoUpdater.on('update-downloaded', async (info) => {
    const w = getWindow && getWindow();
    if (w && !w.isDestroyed()) {
      w.webContents.send('update:status', 'downloaded');
    }
    const { response } = await dialog.showMessageBox(w || undefined, {
      type: 'info',
      title: '更新已就绪',
      message: `DeepSeek Harness Desktop ${info.version} 已下载完成。`,
      detail: '是否现在重启应用并安装更新？',
      buttons: ['立即重启', '稍后'],
      defaultId: 0,
      cancelId: 1,
    });
    if (response === 0) {
      autoUpdater.quitAndInstall(false, true);
    }
  });

  initialized = true;
}

/** Manual check from the Help menu. */
async function checkForUpdates(fromMenu = false) {
  const { autoUpdater } = require('electron-updater');

  if (!initialized) {
    // Auto-update was never set up (e.g. dev mode without a window); wire it now.
    setupUpdater(() => null);
  }

  // The updater silently no-ops when the app has no valid update metadata
  // (e.g. unsigned dev builds on macOS, or a build made with --publish never
  // that lacks app-update.yml). Give the user an explicit hint in that case.
  const hasConfig = (() => {
    try {
      const updater = require('electron-updater');
      return Boolean(updater.autoUpdater && updater.autoUpdater.updateConfigPath);
    } catch {
      return false;
    }
  })();

  if (!hasConfig || !process.resourcesPath.includes('app.asar')) {
    if (fromMenu) {
      dialog.showMessageBox({
        type: 'info',
        title: '检查更新',
        message:
          '当前是开发版或未配置发布源的构建，自动更新不可用。\n\n' +
          '正式安装包（从 GitHub Releases 安装）将自动支持更新。',
      });
    }
    return;
  }

  try {
    await autoUpdater.checkForUpdatesAndNotify();
  } catch (err) {
    if (fromMenu) {
      dialog.showMessageBox({
        type: 'error',
        title: '检查更新失败',
        message: String(err?.message || err),
        buttons: ['好的'],
      });
    }
  }
}

module.exports = { setupUpdater, checkForUpdates };
